[tool.isort]
# config compatible with Black
profile = "black"

[tool.pylint.master]
# jobs=0 means 'use all CPUs'
jobs = 0

[tool.pylint.message_control]
max-line-length = 20
disable = [
    "abstract-method",
    "bad-continuation",
    "bare-except",
    "broad-except",
    "fixme",
    "invalid-name",
    "line-too-long",
    "locally-disabled",
    "logging-fstring-interpolation",
    "missing-docstring",
    "no-member",
    "no-self-use",
    "no-value-for-parameter",
    "protected-access",
    "redefined-outer-name",
    "relative-import",
    "too-few-public-methods",
    "too-many-public-methods",
    "ungrouped-imports",
    "unused-argument",
    "wrong-import-position",
]

[tool.pylint.reports]
output-format = "colorized"

[tool.pylint.format]
logging-modules = [
  "logging",
  "structlog"
]